app/src/main/java/com/icecoldbier/persistence/entities/Paziente.java
package com.icecoldbier.persistence.entities;

import com.icecoldbier.utils.Utils;

import java.sql.Date;

public class Paziente extends User{
    private Date dataNascita;
    private String luogoNascita;
    private String codiceFiscale;
    private char sesso;
    private String foto;
    private String fotoThumb;
    private User medico;


    public Paziente(Integer id, UserType typ, String username, String password, String nome, String cognome, String provinciaAppartenenza, Date dataNascita, String luogoNascita, String codiceFiscale, char sesso, String foto, User medico) {
        super(id, typ, username, password, nome, cognome, provinciaAppartenenza);
        this.dataNascita = dataNascita;
        this.luogoNascita = luogoNascita;
        this.codiceFiscale = codiceFiscale;
        this.sesso = sesso;
        this.foto = (foto == null || foto.equals("")) ? "/photos/" : foto;
        this.fotoThumb = (foto == null || foto.equals("")) ? "/photos/" : foto + "?size=thumbnail";
        this.medico = medico;
    }

    public Date getDataNascita() {
        return dataNascita;
    }

    public void setDataNascita(Date dataNascita) {
        this.dataNascita = dataNascita;
    }

    public String getPrettyDataNascita() {
        return Utils.parseDate(dataNascita);
    }

    public String getLuogoNascita() {
        return luogoNascita;
    }

    public void setLuogoNascita(String luogoNascita) {
        this.luogoNascita = luogoNascita;
    }

    public String getCodiceFiscale() {
        return codiceFiscale;
    }

    public void setCodiceFiscale(String codiceFiscale) {
        this.codiceFiscale = codiceFiscale;
    }

    public char getSesso() {
        return sesso;
    }

    public void setSesso(char sesso) {
        this.sesso = sesso;
    }

    public String getFoto() {
        return foto;
    }

    public void setFoto(String foto) {
        this.foto = foto;
    }

    public String getFotoThumb() {
        return fotoThumb;
    }

    public void setFotoThumb(String fotoThumb) {
        this.fotoThumb = fotoThumb;
    }

    public User getMedico() {
        return medico;
    }

    public void setMedico(User medico) {
        this.medico = medico;
    }

    @Override
    public String toString() {
        return "Paziente{" +
                "data_nascita=" + dataNascita +
                ", luogo_nascita='" + luogoNascita + '\'' +
                ", codice_fiscale='" + codiceFiscale + '\'' +
                ", sesso=" + sesso +
                ", foto='" + foto + '\'' +
                ", id_medico=" + medico.getId() +
                "} " + super.toString();
    }
}

app/src/main/java/com/icecoldbier/persistence/entities/Ticket.java
package com.icecoldbier.persistence.entities;

import com.icecoldbier.utils.Utils;

import java.sql.Timestamp;

public class Ticket {
    private Timestamp dataErogazione;
    private String tipoVisita;
    private String nomeVisita;
    private float costo;

    public Ticket(Timestamp dataErogazione, String tipoVisita, String nomeVisita, float costo) {
        this.dataErogazione = dataErogazione;
        this.tipoVisita = tipoVisita;
        this.nomeVisita = nomeVisita;
        this.costo = costo;
    }

    public Timestamp getDataErogazione() {
        return dataErogazione;
    }

    public void setDataErogazione(Timestamp dataErogazione) {
        this.dataErogazione = dataErogazione;
    }

    public String getPrettyDataErogazione() {
        return Utils.parseTimestamp(dataErogazione);

    }

    public String getTipoVisita() {
        return tipoVisita;
    }

    public void setTipoVisita(String tipoVisita) {
        this.tipoVisita = tipoVisita;
    }

    public String getNomeVisita() {
        return nomeVisita;
    }

    public void setNomeVisita(String nomeVisita) {
        this.nomeVisita = nomeVisita;
    }

    public float getCosto() {
        return costo;
    }

    public void setCosto(float costo) {
        this.costo = costo;
    }
}

app/src/main/java/com/icecoldbier/filters/controllers/MedicoBaseController.java
package com.icecoldbier.filters.controllers;

import com.icecoldbier.persistence.dao.implementations.*;
import com.icecoldbier.persistence.entities.*;
import it.unitn.disi.wp.commons.persistence.dao.exceptions.DAOException;
import it.unitn.disi.wp.commons.persistence.dao.exceptions.DAOFactoryException;
import it.unitn.disi.wp.commons.persistence.dao.factories.DAOFactory;

import javax.servlet.*;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import java.io.IOException;
import java.util.ArrayList;

public class MedicoBaseController implements Filter {
    private PazienteDAO pazienteDAO;
    private MedicoBaseDAO medicoBaseDAO;
    private MedicoSpecialistaDAO medicoSpecialistaDAO;
    private SSPDAO sspDAO;
    private VisitePossibiliDAO visitePossibiliDAO;
    private VisitaBaseDAO visitaBaseDAO;

    public void destroy() {
    }

    public void doFilter(ServletRequest req, ServletResponse resp, FilterChain chain) throws ServletException, IOException {
        HttpServletRequest request = (HttpServletRequest) req;
        HttpServletResponse response = (HttpServletResponse) resp;
        HttpSession session = request.getSession(false);
        String userPath = request.getServletPath();
        final User user = (User)session.getAttribute("user");

        boolean doChain = true;

        if(userPath.equals("/medico-base/lista")){
            ArrayList<Paziente> listaPazienti;
            try{
                String showAllS = request.getParameter("mostraTutti");
                boolean showAll = showAllS == null ? true : Boolean.parseBoolean(showAllS);

                if(showAll){
                    listaPazienti = pazienteDAO.getPazienti();
                }else{
                    listaPazienti = pazienteDAO.getPazientiAssociati(user.getId());
                }

                request.setAttribute("showAll", showAll);
                request.setAttribute("listaPazienti", listaPazienti);
            }catch (DAOException e) {
                doChain = false;
                response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR, "Non è stato possibile recuperare la lista dei pazienti, riprova più tardi");
                e.printStackTrace();
            }
        }else if(userPath.equals("/medico-base/lista-visite-base")){
            int idPaziente = -1, idMedico = user.getId();

            String idPazienteS;
            idPazienteS = request.getParameter("id_paziente");

            try {
                if(idPazienteS != null && !idPazienteS.equals("")){
                    idPaziente = Integer.parseInt(idPazienteS);
                }

            }catch (Exception e){
                e.printStackTrace();
                response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR, "Non è stato possibile recuperare la lista delle visite base, riprova più tardi");
                return;
            }
            try{
                ArrayList<VisitaBase> listaVisite;

                if(idPaziente == -1){
                    listaVisite = visitaBaseDAO.getByMedico(idMedico);
                }else {
                    Paziente paziente = pazienteDAO.getByPrimaryKey(idPaziente);
                    //Se il paziente non è tuo
                    if(!paziente.getMedico().getId().equals(user.getId())){
                        response.sendError(HttpServletResponse.SC_UNAUTHORIZED, "Il paziente non è tuo");
                    }
                    request.setAttribute("paziente", paziente);
                    listaVisite = visitaBaseDAO.getByMedicoAndPaziente(idMedico, idPaziente);
                }

                request.setAttribute("listaVisite", listaVisite);

            }catch (DAOException e) {
                e.printStackTrace();
                response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR, "Non è stato possibile recuperare la lista delle visite base, riprova più tardi");
            }

        }else if(userPath.equals("/medico-base/lista-visite-specialistiche")){
            int idPaziente = -1, idMedico = user.getId();

            String idPazienteS;
            idPazienteS = request.getParameter("id_paziente");

            try {
                if(idPazienteS != null && !idPazienteS.equals("")){
                    idPaziente = Integer.parseInt(idPazienteS);
                }

            }catch (Exception e){
                e.printStackTrace();
            }

            try{
                ArrayList<VisitaSpecialisticaOrSSP> listaVisite = new ArrayList<>();


                if(idPaziente == -1){
                    listaVisite = medicoBaseDAO.getVisiteEsamiByMedico(idMedico);
                }else {
                    Paziente paziente = pazienteDAO.getByPrimaryKey(idPaziente);
                    //Se il paziente non è tuo
                    if(!paziente.getMedico().getId().equals(user.getId())){
                        response.sendError(HttpServletResponse.SC_BAD_REQUEST, "Il paziente non è tuo");
                    }
                    request.setAttribute("paziente", paziente);
                    listaVisite =  medicoBaseDAO.getVisiteEsamiByMedicoAndPaziente(idMedico, idPaziente);
                }

                request.setAttribute("listaVisite", listaVisite);

            }catch (DAOException e) {
                e.printStackTrace();
                response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR, "Non è stato possibile recuperare la lista delle visite specialistiche, riprova più tardi");
            }

        }
        else if(userPath.equals("/medico-base/scheda-paziente")){
            String idS = request.getParameter("id");
            if(idS != null){
                int id = Integer.parseInt(idS);
                try {
                    Paziente p = pazienteDAO.getByPrimaryKey(id);
                    request.setAttribute("paziente", p);

                    //Visite specialistiche possibili
                    ArrayList<VisitaPossibile> visitePossibili = visitePossibiliDAO.getVisitePossibili(User.UserType.medico_specialista);
                    request.setAttribute("visitePossibili", visitePossibili);

                    //Esami ssp possibili
                    ArrayList<VisitaPossibile> esamiPossibili = visitePossibiliDAO.getVisitePossibili(User.UserType.ssp);
                    request.setAttribute("esamiPossibili", esamiPossibili);


                    ArrayList<User> mediciSpecialisti = (ArrayList<User>) medicoSpecialistaDAO.getAll();
                    request.setAttribute("mediciSpecialisti", mediciSpecialisti);

                    ArrayList<SSP> ssp = (ArrayList<SSP>) sspDAO.getAll();
                    request.setAttribute("ssp", ssp);
                    try {
                        User medicoBase = medicoBaseDAO.getByPrimaryKey(p.getMedico().getId());
                        request.setAttribute("medico", medicoBase);
                    } catch (DAOException e) {
                        e.printStackTrace();
                        request.setAttribute("medico", null);
                    }
                } catch (DAOException e) {
                    e.printStackTrace();
                    doChain = false;
                    response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR, "Non è stato possibile recuperare i dettagli del paziente, riprova più tardi");
                }
            }

        }


        if(doChain)
            chain.doFilter(req, resp);
    }

    public void init(FilterConfig config) throws ServletException {
        DAOFactory daoFactory = (DAOFactory) config.getServletContext().getAttribute("daoFactory");
        if (daoFactory == null) {
            throw new ServletException("Impossible to get dao factory ");
        }
        try {
            pazienteDAO = daoFactory.getDAO(PazienteDAO.class);
            medicoBaseDAO = daoFactory.getDAO(MedicoBaseDAO.class);
            medicoSpecialistaDAO = daoFactory.getDAO(MedicoSpecialistaDAO.class);
            sspDAO = daoFactory.getDAO(SSPDAO.class);
            visitePossibiliDAO = daoFactory.getDAO(VisitePossibiliDAO.class);
            visitaBaseDAO = daoFactory.getDAO(VisitaBaseDAO.class);
        } catch (DAOFactoryException e) {
            throw new ServletException(e.getMessage());
        }
    }
}

app/src/main/webapp/pages/medico_base/lista_pazienti.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib uri="/WEB-INF/customTags/miniProfileTag.tld" prefix="mp" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<jsp:useBean id="showAll" scope="request" type="java.lang.Boolean"/>


<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Medico Base - Lista Pazienti</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css"
          href="https://cdn.datatables.net/v/bs4/dt-1.10.20/r-2.2.3/datatables.min.css"/>
    <link rel="stylesheet" type="text/css" href="../css/style.css">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

</head>
<body>
<%@ include file="navbar.html" %>

<% response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate"); %>

<div class="container">
    <h1>Lista pazienti</h1>
    <div class="div-centered">
        <c:choose>
            <c:when test="${showAll}">
                <a class="btn btn-primary mb-3"
                   href="lista?mostraTutti=false"
                   role="button">Mostra solo i tuoi pazienti</a>
            </c:when>
            <c:otherwise>
                <a class="btn btn-primary mb-3"
                   href="lista?mostraTutti=true"
                   role="button">Mostra tutti i pazienti</a>
            </c:otherwise>
        </c:choose>
    </div>

    <table class="datatable table table-striped">
        <thead class="thead-dark">
        <tr>
            <th class="all" scope="col">Foto</th>
            <th class="all default-sort" scope="col">Nome e cognome</th>
            <th class="min-sm" scope="col">Sesso</th>
            <th class="min-sm" scope="col">Data di nascita</th>
            <th class="min-md" scope="col">Luogo di nascita</th>
            <th class="min-md" scope="col">Provincia</th>
            <th class="min-lg" scope="col">Codice fiscale</th>
            <th class="all" scope="col">Scheda</th>
        </tr>
        </thead>
        <tbody>
        <jsp:useBean id="listaPazienti" scope="request"
                     type="java.util.List<com.icecoldbier.persistence.entities.Paziente>"/>
        <c:forEach var="p" items="${listaPazienti}">
            <tr>
                <td>
                    <img class="profile-picture-thumbnail" src="<c:out value="${p.fotoThumb}"/>" height="48" width="48">
                </td>
                <td>
                    <mp:miniProfileTag paziente="${p}"/>
                    <c:if test="${user.id == p.medico.id}">
                        <span class="badge badge-success"><i class="material-icons badge-icon">check</i></span>
                    </c:if>
                </td>
                <td><c:out value="${p.sesso}"/></td>
                <td><c:out value="${p.prettyDataNascita}"/></td>
                <td><c:out value="${p.luogoNascita}"/></td>
                <td><c:out value="${p.provinciaAppartenenza}"/></td>
                <td><c:out value="${p.codiceFiscale}"/></td>
                <td><a class="btn btn-primary mb-3 icon-white"
                       href="scheda-paziente?id=<c:out value="${p.id}"/>"
                       role="button"><i class="material-icons">open_in_new</i></a></td>

            </tr>
        </c:forEach>
        </tbody>
    </table>
</div>

<script>
    var specialista = false;
</script>

<script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.20/r-2.2.3/datatables.min.js"></script>
<script src="https://cdn.jsdelivr.net/gh/xcash/bootstrap-autocomplete@v2.3.0/dist/latest/bootstrap-autocomplete.min.js"></script>

<script src="../js/init_datatables.js"></script>
<script src="../js/ricerca_pazienti.js"></script>
</body>
</html>

app/src/main/webapp/pages/medico_base/lista_visite.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib uri="/WEB-INF/customTags/ellipsizeTag.tld" prefix="ct" %>
<%@ taglib uri="/WEB-INF/customTags/miniProfileTag.tld" prefix="mp" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<jsp:useBean id="listaVisite" scope="request" type="java.util.List<com.icecoldbier.persistence.entities.VisitaBase>"/>


<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Medico Base - Lista Visite Base</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../css/style.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.20/r-2.2.3/datatables.min.css"/>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

</head>
<body>
<%@ include file="navbar.html" %>

<% response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate"); %>

<div class="container">
    <c:choose>
        <c:when test="${empty paziente}">
            <h1>Lista visite base</h1>
        </c:when>
        <c:otherwise>
            <h1>Lista visite base di <c:out value="${paziente.nome} ${paziente.cognome}"/></h1>
        </c:otherwise>
    </c:choose>


        <table class="datatable table table-striped">
            <thead class="thead-dark">
            <tr>
                <th class="all" scope="col">Foto</th>
                <th class="all" scope="col">Paziente</th>
                <th class="all default-sort" scope="col">Data erogazione</th>
                <th class="min-sm" scope="col">Ricetta</th>
            </tr>
            </thead>
            <tbody>
            <c:forEach var="v" items="${listaVisite}">
                <tr>
                    <td>
                        <img class="profile-picture-thumbnail" src="<c:out value="${v.paziente.fotoThumb}"/>" height="48" width="48">
                    </td>
                    <td>
                        <mp:miniProfileTag paziente="${v.paziente}"/>
                        <c:if test="${user.id == v.paziente.medico.id}">
                            <span class="badge badge-success"><i class="material-icons badge-icon">check</i></span>
                        </c:if>
                    </td>
                    <td><c:out value="${v.prettyDataErogazione}"/></td>
                    <td>
                        <c:choose>
                            <c:when test="${empty v.ricetta}">
                                Nessuna ricetta
                            </c:when>
                            <c:otherwise>
                                <ct:ellipsizeTag maxLength="30"><c:out value="${v.ricetta.nome}"/></ct:ellipsizeTag>
                            </c:otherwise>
                        </c:choose>
                    </td>
                </tr>
            </c:forEach>
            </tbody>
        </table>
</div>

<script>
    var specialista = false;
</script>

<script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.20/r-2.2.3/datatables.min.js"></script>
<script src="https://cdn.jsdelivr.net/gh/xcash/bootstrap-autocomplete@v2.3.0/dist/latest/bootstrap-autocomplete.min.js"></script>

<script src="../js/init_datatables.js"></script>
<script src="../js/ricerca_pazienti.js"></script>
</body>
</html>