app/src/main/java/com/icecoldbier/persistence/entities/Paziente.java
package com.icecoldbier.persistence.entities;

import com.icecoldbier.utils.Utils;

import java.sql.Date;

public class Paziente extends User{
    private Date dataNascita;
    private String luogoNascita;
    private String codiceFiscale;
    private char sesso;
    private String foto;
    private String fotoThumb;
    private User medico;


    public Paziente(Integer id, UserType typ, String username, String password, String nome, String cognome, String provinciaAppartenenza, Date dataNascita, String luogoNascita, String codiceFiscale, char sesso, String foto, User medico) {
        super(id, typ, username, password, nome, cognome, provinciaAppartenenza);
        this.dataNascita = dataNascita;
        this.luogoNascita = luogoNascita;
        this.codiceFiscale = codiceFiscale;
        this.sesso = sesso;
        this.foto = (foto == null || foto.equals("")) ? "/photos/" : foto;
        this.fotoThumb = (foto == null || foto.equals("")) ? "/photos/" : foto + "?size=thumbnail";
        this.medico = medico;
    }

    public Date getDataNascita() {
        return dataNascita;
    }

    public void setDataNascita(Date dataNascita) {
        this.dataNascita = dataNascita;
    }

    public String getPrettyDataNascita() {
        return Utils.parseDate(dataNascita);
    }

    public String getLuogoNascita() {
        return luogoNascita;
    }

    public void setLuogoNascita(String luogoNascita) {
        this.luogoNascita = luogoNascita;
    }

    public String getCodiceFiscale() {
        return codiceFiscale;
    }

    public void setCodiceFiscale(String codiceFiscale) {
        this.codiceFiscale = codiceFiscale;
    }

    public char getSesso() {
        return sesso;
    }

    public void setSesso(char sesso) {
        this.sesso = sesso;
    }

    public String getFoto() {
        return foto;
    }

    public void setFoto(String foto) {
        this.foto = foto;
    }

    public String getFotoThumb() {
        return fotoThumb;
    }

    public void setFotoThumb(String fotoThumb) {
        this.fotoThumb = fotoThumb;
    }

    public User getMedico() {
        return medico;
    }

    public void setMedico(User medico) {
        this.medico = medico;
    }

    @Override
    public String toString() {
        return "Paziente{" +
                "data_nascita=" + dataNascita +
                ", luogo_nascita='" + luogoNascita + '\'' +
                ", codice_fiscale='" + codiceFiscale + '\'' +
                ", sesso=" + sesso +
                ", foto='" + foto + '\'' +
                ", id_medico=" + medico.getId() +
                "} " + super.toString();
    }
}

app/src/main/java/com/icecoldbier/persistence/entities/VisitaSSP.java
package com.icecoldbier.persistence.entities;

import com.icecoldbier.utils.Utils;

import java.sql.Timestamp;

public class VisitaSSP extends Visita {
    private VisitaPossibile tipo_visita;
    private boolean erogata;
    private Timestamp dataPrescrizione;
    private SSP ssp;
    private User medicoBase;

    public VisitaSSP(int id, Paziente paziente, Timestamp dataErogazione, VisitaPossibile tipo_visita, boolean erogata, Timestamp dataPrescrizione, SSP ssp, User medicoBase) {
        super(id, paziente, dataErogazione);
        this.tipo_visita = tipo_visita;
        this.erogata = erogata;
        this.dataPrescrizione = dataPrescrizione;
        this.ssp = ssp;
        this.medicoBase = medicoBase;
    }

    public VisitaPossibile getTipo_visita() {
        return tipo_visita;
    }

    public void setTipo_visita(VisitaPossibile tipo_visita) {
        this.tipo_visita = tipo_visita;
    }

    public boolean isErogata() {
        return erogata;
    }

    public void setErogata(boolean erogata) {
        this.erogata = erogata;
    }

    public Timestamp getDataPrescrizione() {
        return dataPrescrizione;
    }

    public String getPrettyDataPrescrizione() {
        return Utils.parseTimestamp(dataPrescrizione);
    }

    public void setDataPrescrizione(Timestamp dataPrescrizione) {
        this.dataPrescrizione = dataPrescrizione;
    }

    public SSP getSsp() {
        return ssp;
    }

    public void setSsp(SSP ssp) {
        this.ssp = ssp;
    }

    public User getMedicoBase() {
        return medicoBase;
    }

    public void setMedicoBase(User medicoBase) {
        this.medicoBase = medicoBase;
    }
}

app/src/main/java/com/icecoldbier/filters/controllers/MedicoSpecialistaController.java
package com.icecoldbier.filters.controllers;

import com.icecoldbier.persistence.dao.implementations.MedicoBaseDAO;
import com.icecoldbier.persistence.dao.implementations.MedicoSpecialistaDAO;
import com.icecoldbier.persistence.dao.implementations.PazienteDAO;
import com.icecoldbier.persistence.dao.implementations.VisitaSpecialisticaDAO;
import com.icecoldbier.persistence.entities.Paziente;
import com.icecoldbier.persistence.entities.User;
import com.icecoldbier.persistence.entities.VisitaSpecialistica;
import it.unitn.disi.wp.commons.persistence.dao.exceptions.DAOException;
import it.unitn.disi.wp.commons.persistence.dao.exceptions.DAOFactoryException;
import it.unitn.disi.wp.commons.persistence.dao.factories.DAOFactory;

import javax.servlet.*;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import java.io.IOException;
import java.util.ArrayList;

public class MedicoSpecialistaController implements Filter {

    private MedicoSpecialistaDAO medicoSpecialistaDAO;
    private PazienteDAO pazienteDAO;
    private VisitaSpecialisticaDAO visitaSpecialisticaDAO;
    private MedicoBaseDAO medicoBaseDAO;
    public void destroy() {
    }

    public void doFilter(ServletRequest req, ServletResponse resp, FilterChain chain) throws ServletException, IOException {
        HttpServletRequest request = (HttpServletRequest) req;
        HttpServletResponse response = (HttpServletResponse) resp;
        HttpSession session = request.getSession(false);
        String userPath = request.getServletPath();
        User user = (User)session.getAttribute("user");

        boolean error = false;

        if(userPath.equals("/medico-specialista/lista")){
            ArrayList<Paziente> listaPazienti;
            try{
                String showAllS = request.getParameter("mostraTutti");
                boolean showAll = showAllS == null ? true : Boolean.parseBoolean(showAllS);

                if(showAll){
                    listaPazienti = pazienteDAO.getPazienti();
                }else{
                    listaPazienti = medicoSpecialistaDAO.getListaPazientiAssociati(user.getId());
                }

                request.setAttribute("showAll", showAll);
                request.setAttribute("listaPazientiSpecialista", listaPazienti);
            }catch (DAOException e) {
                response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR, "Non è stato possibile recuperare la lista dei pazienti, riprova più tardi");
                e.printStackTrace();
                return;
            }
        }else if(userPath.equals(("/medico-specialista/visite"))){
            ArrayList<VisitaSpecialistica> visite = null;
            try {
                visite = medicoSpecialistaDAO.getListaVisitePazienti(user.getId());
                request.setAttribute("visite", visite);
            } catch (DAOException ex) {
                ((HttpServletResponse)resp).sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR, ex.getMessage());
                ex.printStackTrace();
            }
        }else if(userPath.equals("/medico-specialista/visite/dettagli-visita")){
            String idS = request.getParameter("id");
            VisitaSpecialistica visita = null;
            if(idS != null){
                int id;
                try{
                    id = Integer.parseInt(idS);
                }catch (Exception e){
                    response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR, "Non è stato possibile recuperare la lista delle visite specialistiche, riprova più tardi");
                    return;
                }

                try {
                    visita = visitaSpecialisticaDAO.getByPrimaryKey(id);
                    request.setAttribute("visita", visita);
                } catch (DAOException ex) {
                    ((HttpServletResponse)resp).sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR, ex.getMessage());
                    ex.printStackTrace();
                }
            }
        }else if(userPath.equals(("/medico-specialista/scheda-paziente"))){
            String idS = request.getParameter("id");
            Paziente paziente = null;
            User medico = null;
            if(idS != null){
                try {
                    int id = Integer.parseInt(idS);
                    paziente = pazienteDAO.getByPrimaryKey(id);
                    medico = medicoBaseDAO.getByPrimaryKey(paziente.getMedico().getId());
                    request.setAttribute("paziente", paziente);
                    request.setAttribute("medico", medico);
                } catch (DAOException ex) {
                    response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR, "Non è stato possibile recuperare i dettagli del paziente, riprova più tardi.");
                    ex.printStackTrace();
                }
            }else{
                response.sendError(HttpServletResponse.SC_BAD_REQUEST, "Id non valido o mancante");
            }
        }

        if(!error)
            chain.doFilter(req, resp);
    }

    public void init(FilterConfig config) throws ServletException {
        DAOFactory daoFactory = (DAOFactory) config.getServletContext().getAttribute("daoFactory");
        if (daoFactory == null) {
            throw new ServletException("Impossible to get dao factory ");
        }
        try {
            medicoSpecialistaDAO = daoFactory.getDAO(MedicoSpecialistaDAO.class);
        } catch (DAOFactoryException e) {
            throw new ServletException(e.getMessage());
        }
        try {
            pazienteDAO = daoFactory.getDAO(PazienteDAO.class);
        } catch (DAOFactoryException e) {
            throw new ServletException(e.getMessage());
        }
        try {
            visitaSpecialisticaDAO = daoFactory.getDAO(VisitaSpecialisticaDAO.class);
        } catch (DAOFactoryException e) {
            throw new ServletException(e.getMessage());
        }
        try {
            medicoBaseDAO = daoFactory.getDAO(MedicoBaseDAO.class);
        } catch (DAOFactoryException e) {
            throw new ServletException(e.getMessage());
        }
    }

}

app/src/main/java/com/icecoldbier/servlets/MedicoSpecialistaServlet.java
package com.icecoldbier.servlets;

import com.icecoldbier.persistence.dao.implementations.MedicoBaseDAO;
import com.icecoldbier.persistence.dao.implementations.MedicoSpecialistaDAO;
import com.icecoldbier.persistence.dao.implementations.PazienteDAO;
import com.icecoldbier.persistence.dao.implementations.VisitaSpecialisticaDAO;
import com.icecoldbier.persistence.entities.Report;
import com.icecoldbier.persistence.entities.Ricetta;
import com.icecoldbier.persistence.entities.User;
import com.icecoldbier.persistence.entities.VisitaSpecialistica;
import com.icecoldbier.utils.Utils;
import it.unitn.disi.wp.commons.persistence.dao.exceptions.DAOException;
import it.unitn.disi.wp.commons.persistence.dao.exceptions.DAOFactoryException;
import it.unitn.disi.wp.commons.persistence.dao.factories.DAOFactory;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;


@WebServlet(name = "MedicoSpecialistaServlet", urlPatterns = {"/medico-specialista/visite/eroga"})
public class MedicoSpecialistaServlet extends HttpServlet {
    private MedicoBaseDAO medicoBaseDAO;
    private PazienteDAO pazienteDAO;
    private MedicoSpecialistaDAO medicoSpecialistaDAO;
    private VisitaSpecialisticaDAO visitaSpecialisticaDAO;
    
    @Override
    public void init() throws ServletException {
        DAOFactory daoFactory = (DAOFactory) super.getServletContext().getAttribute("daoFactory");
        if (daoFactory == null) {
            throw new ServletException("Impossible to get dao factory for user storage system");
        }
        try {
            medicoBaseDAO = daoFactory.getDAO(MedicoBaseDAO.class);
            pazienteDAO = daoFactory.getDAO(PazienteDAO.class);
            medicoSpecialistaDAO = daoFactory.getDAO(MedicoSpecialistaDAO.class);
            visitaSpecialisticaDAO = daoFactory.getDAO(VisitaSpecialisticaDAO.class);
        } catch (DAOFactoryException e) {
            throw new ServletException("Impossible to get dao factory for medico base storage system");
        }
    }
    
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws IOException{
        request.setCharacterEncoding("UTF-8");
        String userPath = request.getServletPath();
        HttpSession session =  request.getSession(false);
        User user = (User) session.getAttribute("user");
        String contextPath = Utils.getServletContextPath(request.getServletContext());
        
        if(userPath.equals("/medico-specialista/visite/eroga")){
            String idPaziente = request.getParameter("idPaziente");
            String idMedicoSpecialista = request.getParameter("idMedicoSpecialista");
            String idMedicoBase = request.getParameter("idMedicoBase");
            String idVisita = request.getParameter("idVisita");
            String textReport = request.getParameter("textReport");
            String textRicetta = request.getParameter("textRicetta");
            String usernamePaziente = request.getParameter("usernamePaziente");
            
            if(idPaziente != null && idMedicoSpecialista!= null && idMedicoBase!=null && idVisita!=null && textReport!=null){
                int idPaz = Integer.parseInt(idPaziente);
                int idVis = Integer.parseInt(idVisita);
                int idMedBas = Integer.parseInt(idMedicoBase);
                int idMedSpec = Integer.parseInt(idMedicoSpecialista);
                VisitaSpecialistica visita = null;
                Report report = new Report(textReport);
                String messaggio = "Report visita: " + textReport + "\n";
                String oggetto = "Esito visita specialistica";
                
                if(textRicetta.equals("")){
                    try {
                        medicoSpecialistaDAO.erogaVisita(idVis,idPaz,idMedBas,report);
                        visita = visitaSpecialisticaDAO.getByPrimaryKey(idVis);
                        session.setAttribute("successMessage", "Visita erogata con successo");
                        response.sendRedirect(response.encodeRedirectURL(contextPath + "medico-specialista/visite/dettagli-visita?id=" + idVisita));
                    } catch (DAOException ex) {
                        session.setAttribute("errorMessage", "Errore nell'erogare la visita senza ricetta, riprova più tardi");
                        ex.printStackTrace();
                    }
                }else{
                    Ricetta ricetta = new Ricetta(textRicetta,false);
                    try {
                        medicoSpecialistaDAO.erogaVisitaConRicetta(idVis, idPaz, idMedBas, report, ricetta);
                        visita = visitaSpecialisticaDAO.getByPrimaryKey(idVis);
                        messaggio += "Ricetta: " + textRicetta + "\n";
                        session.setAttribute("successMessage", "Visita erogata con successo");
                        response.sendRedirect(response.encodeRedirectURL(contextPath + "medico-specialista/visite/dettagli-visita?id=" + idVisita));
                    } catch (DAOException ex) {
                        session.setAttribute("errorMessage", "Errore nell'erogare la visita con ricetta, riprova più tardi");
                        ex.printStackTrace();
                    }
                }
                
                try {
                    Utils.sendMail(pazienteDAO.getByPrimaryKey(Integer.parseInt(idPaziente)), oggetto, messaggio);
                } catch (DAOException ex) {
                    session.setAttribute("errorMessage", "Errore nel trovare l'utente a cui inviare la mail");
                    ex.printStackTrace();
                } catch (MessagingException ex) {
                    session.setAttribute("errorMessage", "Errore nell'inviare la mail");
                    ex.printStackTrace();
                }
            }else{
                response.sendError(HttpServletResponse.SC_BAD_REQUEST, "Id mancanti");
            }
        }
    }
    

}

app/src/main/webapp/pages/medico_specialista/dettagli_visita.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib uri="/WEB-INF/customTags/ellipsizeTag.tld" prefix="ct" %>
<%@ taglib uri="/WEB-INF/customTags/miniProfileTag.tld" prefix="mp" %>
<jsp:useBean id="visita" scope="request" type="com.icecoldbier.persistence.entities.VisitaSpecialistica"/>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Dettagli visita</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../../css/style.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
<%@ include file="navbar.html" %>

<% response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate"); %>

<div class="container">
    <h1>Visita di <c:out value="${visita.paziente.toStringNomeCognome()}"/></h1>
    <div class="row">
        <div class="col-12 col-lg-6">
            <table class="table profile-table">
                <tbody>
                    <tr>
                        <td colspan="2" style="text-align: center">
                            <img class="profile-picture" src="<c:out value="${visita.paziente.foto}"/>">
                        </td>
                    </tr>

                    <tr>
                        <th><b>Tipo visita</b></th>
                        <td><c:out value="${visita.tipo_visita.nome}"/></td>
                    </tr>
                    <tr>
                        <th><b>Descrizione visita</b></th>
                        <td><c:out value="${visita.tipo_visita.nome}"/></td>
                    </tr>
                    <tr>
                        <th><b>Paziente</b></th>
                        <td> <mp:miniProfileTag paziente="${visita.paziente}"/></td>
                    </tr>
                    <tr>
                        <th><b>Codice Fiscale</b></th>
                        <td><c:out value="${visita.paziente.codiceFiscale}"/></td>
                    </tr>
                    <tr>
                        <th><b>Data di prescrizione</b></th>
                        <td><c:out value="${visita.prettyDataPrescrizione}"/></td>
                    </tr>
                    <tr>
                        <th><b>Erogata</b></th>
                        <td>
                            <c:choose>
                                <c:when test="${visita.erogata}">Si</c:when>
                                <c:otherwise>No</c:otherwise>
                            </c:choose>
                        </td>
                    </tr>
                    <tr>
                        <th><b>Medico di base</b></th>
                        <td> <mp:miniProfileTag user="${visita.medicoBase}"/> </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-12 col-lg-6  funzioni-col">
            <h2>Funzioni</h2>
            <div class="card-deck">
                <div class="card border-dark mb-3" style="max-width: 100rem;">
                    <div class="card-header">Eroga visita specialistica</div>
                    <div class="card-body text-dark">
                        <p class="card-text">Eroga una visita specialistica con la possibilità di associare
                            una ricetta.</p>
                        <button type="button" class="btn btn-primary stretched-link" data-toggle="modal"
                                data-target="#modaleErogaVisitaSpecialistica" <c:if test="${visita.erogata}">disabled</c:if> >
                            Apri
                        </button>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
</div>

<div class="modal fade" id="modaleErogaVisitaSpecialistica" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <form method="post" action="eroga">
                <input type="hidden" name="idPaziente" value="<c:out value="${visita.paziente.id}"/>">
                <input type="hidden" name="idMedicoSpecialista" value="<c:out value="${visita.medicoSpecialista.id}"/>">
                <input type="hidden" name="idMedicoBase" value="<c:out value="${visita.medicoBase.id}"/>">
                <input type="hidden" name="idVisita" value="<c:out value="${visita.id}"/>">
                <input type="hidden" name="usernamePaziente" value="<c:out value="${visita.paziente.username}"/>">
                <div class="modal-header">
                    <h5 class="modal-title">Eroga una visita specialistica</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Chiudi">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="textRicetta">Ricetta</label>
                        <textarea class="form-control" name="textRicetta" id="textRicetta" rows="3"
                                  placeholder="Inserisci qua l'oggetto della ricetta. Lasciando questo campo vuoto non verrà inserita alcuna ricetta"></textarea>

                    </div>
                    <div class="form-group">
                        <label for="textReport">Report</label>
                        <textarea class="form-control" name="textReport" id="textReport" rows="3"
                                  placeholder="Inserisci qua l'esito del report. Si prega di compilarlo"
                                  required></textarea>

                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Annulla</button>
                    <button type="submit" class="btn btn-primary">Eroga</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    var specialista = true;
</script>
                
<script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.20/r-2.2.3/datatables.min.js"></script>
<script src="https://cdn.jsdelivr.net/gh/xcash/bootstrap-autocomplete@v2.3.0/dist/latest/bootstrap-autocomplete.min.js"></script>

<script src="../../js/init_datatables.js"></script>
<script src="../../js/ricerca_pazienti.js"></script>

<script src="../../js/init_non_datatable_popover.js"></script>


<%--These are the success and error modals--%>
<%@ include file="../../WEB-INF/fragments/statusModals.jspf" %>
</body>
</html>

app/src/main/webapp/pages/medico_specialista/lista_pazienti.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib uri="/WEB-INF/customTags/ellipsizeTag.tld" prefix="ct" %>
<%@ taglib uri="/WEB-INF/customTags/miniProfileTag.tld" prefix="mp" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<jsp:useBean id="listaPazientiSpecialista" scope="request" type="java.util.List<com.icecoldbier.persistence.entities.Paziente>"/>
<jsp:useBean id="showAll" scope="request" type="java.lang.Boolean"/>


<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Medico Specialista - Lista Pazienti</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css"
          href="https://cdn.datatables.net/v/bs4/dt-1.10.20/r-2.2.3/datatables.min.css"/>
    <link rel="stylesheet" type="text/css" href="../css/style.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

</head>
<body>
<%@ include file="navbar.html" %>

<% response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate"); %>

<div class="container">
    <h1>Lista pazienti</h1>

    <div class="div-centered">
        <c:choose>
            <c:when test="${showAll}">
                <a class="btn btn-primary mb-3"
                   href="lista?mostraTutti=false"
                   role="button">Mostra solo i tuoi pazienti</a>
            </c:when>
            <c:otherwise>
                <a class="btn btn-primary mb-3"
                   href="lista?mostraTutti=true"
                   role="button">Mostra tutti i pazienti</a>
            </c:otherwise>
        </c:choose>
    </div>

    <table class="datatable table table-striped table-hover">
        <thead class="thead-dark">
        <tr>
            <th class="all" scope="col">Foto</th>
            <th class="all default-sort" scope="col">Paziente</th>
            <th class="all" scope="col">Sesso</th>
            <th class="min-md" scope="col">Data di nascita</th>
            <th class="min-md" scope="col">Luogo di nascita</th>
            <th class="min-lg" scope="col">Codice fiscale</th>
            <th class="min-lg" scope="col">Scheda</th>

        </tr>
        </thead>
        <tbody>
        <c:forEach var="p" items="${listaPazientiSpecialista}">
            <tr>
                <td>
                    <img class="profile-picture-thumbnail" src="<c:out value="${p.fotoThumb}"/>" height="48" width="48">
                </td>
                <td><mp:miniProfileTag paziente="${p}"/></td>
                <td><c:out value="${p.sesso}"/></td>
                <td><c:out value="${p.prettyDataNascita}"/></td>
                <td><c:out value="${p.luogoNascita}"/></td>
                <td><c:out value="${p.codiceFiscale}"/></td>
                <td><a class="btn btn-primary mb-3 icon-white"
                       href="scheda-paziente?id=<c:out value="${p.id}"/>"
                       role="button"><i class="material-icons">open_in_new</i></a></td>

            </tr>
        </c:forEach>
        </tbody>
    </table>
</div>

<script>
    var specialista = true;
</script>

<script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.20/r-2.2.3/datatables.min.js"></script>
<script src="https://cdn.jsdelivr.net/gh/xcash/bootstrap-autocomplete@v2.3.0/dist/latest/bootstrap-autocomplete.min.js"></script>

<script src="../js/init_datatables.js"></script>
<script src="../js/ricerca_pazienti.js"></script>
</body>
</html>